### ISSUE TITLE
Changing range patterns also affects ranges that used to be part of same range

### ISSUE THREAD

**Issue by danielweidman** [danielweidman/Suleis#3]
Steps to reproduce:
Add a section from 1 to 100
Add a section from 25 to 75
Set color of section from 1 to 24 to blue

Expected behavior:
Because the section from 1 to 100 was split when the section in the middle of it was created, the section from 1 to 24 and the section from 76 to 100 should now act independently. 

Actual behavior:
The sections are still linked by same pattern object. Setting the 1-24 to blue also changes the 76-100 to blue.

**Comment by danielweidman** [comment]
Alternatively, we could try and deal with this by making it clear in the UI that the sections are still liked, basically allowing for discontinuous sections. Not sure how to indicate this to user intuitively though.

**Comment by L-crooks** [comment]
> Alternatively, we could try and deal with this by making it clear in the UI that the sections are still liked, basically allowing for discontinuous sections. Not sure how to indicate this to user intuitively though.

we could have the numbering repeat if it's the same section, but idk if that would be intuitive

**Comment by danielweidman** [comment]
Fixed in commit https://github.com/danielweidman/Suleis/commit/c92948d0245175768a6e27e201bd4369f31182c5
